name: ci_main_docker

on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        uses: kzrnm/get-net-sdk-project-versions-action@v2
        id: get-version
        with:
          proj-path: src/AspNetCoreApi1Sample/AspNetCoreApi1Sample.csproj


      -
        name: Docker meta
        id: meta-api1
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_ORG }}/itfoxtec
          tags: |            
            type=raw,value=aspnetcore-api1-sample-${{ steps.get-version.outputs.version }}
            type=raw,value=aspnetcore-api1-sample-latest,enable=true
      -
        name: Docker meta
        id: meta-api2
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_ORG }}/itfoxtec
          tags: |     
            type=raw,value=aspnetcore-api2-sample-${{ steps.get-version.outputs.version }}
            type=raw,value=aspnetcore-api2-sample-latest,enable=true
      -
        name: Docker meta
        id: meta-oidc-down-all
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_ORG }}/itfoxtec
          tags: |     
            type=raw,value=aspnet-oidc-allup-sample-${{ steps.get-version.outputs.version }}
            type=raw,value=aspnet-oidc-allup-sample-latest,enable=true
      -
        name: Docker meta
        id: meta-saml-up
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_ORG }}/itfoxtec
          tags: |     
            type=raw,value=aspnetcore-saml-idp-sample-${{ steps.get-version.outputs.version }}
            type=raw,value=aspnetcore-saml-idp-sample-latest,enable=true
      -
        name: Docker meta
        id: meta-ext-login-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_ORG }}/itfoxtec
          tags: |     
            type=raw,value=external-login-api-sample-${{ steps.get-version.outputs.version }}
            type=raw,value=external-login-api-sample-latest,enable=true


      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      -
        name: Build and push AspNetCoreApi1Sample
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/AspNetCoreApi1Sample/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: ${{ steps.meta-api1.outputs.tags }}
          labels: ${{ steps.meta-api1.outputs.labels }}
      -
        name: Build and push AspNetCoreApi2Sample
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/AspNetCoreApi2Sample/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: ${{ steps.meta-api2.outputs.tags }}
          labels: ${{ steps.meta-api2.outputs.labels }}
      -
        name: Build and push AspNetCoreOidcAuthCodeAllUpPartiesSample
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/AspNetCoreOidcAuthCodeAllUpPartiesSample/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: ${{ steps.meta-oidc-down-all.outputs.tags }}
          labels: ${{ steps.meta-oidc-down-all.outputs.labels }}
      -
        name: Build and push AspNetCoreSamlIdPSample
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/AspNetCoreSamlIdPSample/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: ${{ steps.meta-saml-up.outputs.tags }}
          labels: ${{ steps.meta-saml-up.outputs.labels }}
      -
        name: Build and push ExternalLoginApiSample
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/ExternalLoginApiSample/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: ${{ steps.meta-ext-login-api.outputs.tags }}
          labels: ${{ steps.meta-ext-login-api.outputs.labels }}